// Generated by generate_design_system.py from tokens.json and subjects.py.
// Do not edit by hand.
// Regenerate from ios/Packages/Tonight/codegen/design:
//   python3 generate_design_system.py

import Foundation

public enum TonightPalette {
    public static let cream = "#fff4e2"
    public static let creamDot = "#f6e2c3"
    public static let ink = "#2e2550"
    public static let inkSoft = "#6c6484"
    public static let white = "#ffffff"
    public static let sun = "#ffc928"
    public static let sunEdge = "#e0a400"
    public static let sky = "#59b4ff"
    public static let skyEdge = "#2f86d6"
    public static let mint = "#4fcf9f"
    public static let mintEdge = "#2a9e72"
    public static let berry = "#ec4d86"
    public static let berryEdge = "#b82c62"
    public static let mango = "#ff8a3d"
    public static let mangoSoft = "#ffe6d3"
    public static let grape = "#7b61e0"
    public static let grapeEdge = "#5a41bd"
    public static let grapeSoft = "#ece7fd"
    public static let star = "#ffc928"
    public static let starEdge = "#e0a400"
    public static let starEmpty = "#eadfcf"
    public static let toyEdge = "#e6d6bd"
    public static let pBg = "#fbf7f0"
    public static let pCard = "#ffffff"
    public static let pInk = "#2e2550"
    public static let pInkSoft = "#6c6484"
    public static let pLine = "#ece4d6"
    public static let pAccent = "#4b3a8f"
    public static let pAccentInk = "#ffffff"
    public static let pSuccess = "#1f7a52"
    public static let pSuccessSoft = "#e3f4ea"
    public static let pWarnSoft = "#fff1d6"
    public static let pWarnInk = "#7a5200"
    public static let pError = "#9a3b2f"
    public static let pErrorSoft = "#f8ebe7"
    public static let focus = "#2e2550"
}

public enum TonightType {
    public enum Font {
        public static let child = "Fredoka, 'Noto Sans Devanagari', system-ui, sans-serif"
        public static let parent = "Nunito, 'Noto Sans Devanagari', system-ui, sans-serif"
        public static let parentDisplay = "Fredoka, Nunito, sans-serif"
    }

    public enum Text {
        public static let cLabel = 20
        public static let cBody = 24
        public static let cRead = 30
        public static let cTitle = 34
        public static let cHero = 44
        public static let cGlyph = 64
        public static let cGlyphXl = 96
        public static let pXs = 12
        public static let pSm = 14
        public static let pBase = 16
        public static let pLg = 18
        public static let pTitle = 28
        public static let pHero = 34
    }

    public enum Weight {
        public static let cRegular = 600
        public static let cBold = 700
        public static let pRegular = 400
        public static let pSemibold = 700
        public static let pBold = 800
    }

    public enum Leading {
        public static let tight = 1.1
        public static let normal = 1.4
        public static let read = 1.65
    }
}

public enum TonightSpace {
    public static let n1 = 4
    public static let n2 = 8
    public static let n3 = 12
    public static let n4 = 16
    public static let n5 = 20
    public static let n6 = 24
    public static let n8 = 32
    public static let n10 = 40
}

public enum TonightRadius {
    public static let sm = 10
    public static let md = 16
    public static let lg = 22
    public static let xl = 28
    public static let badge = "32%"
    public static let pill = 999
}

public enum TonightSize {
    public static let tapParent = 48
    public static let tapChild = 64
    public static let tapChildLg = 88
    public static let tapChildHero = 120
    public static let frameW = 390
    public static let frameH = 844
}

public enum TonightEdge {
    public static let toy = 8
    public static let toySm = 5
    public static let pressDepth = 6
}

/// Reserved durations and easings. v1 screens stay still (TonightMotion.animationsInV1 is false).
public enum TonightMotionToken {
    public static let durInstant = "80ms"
    public static let durQuick = "150ms"
    public static let durBase = "240ms"
    public static let durSlow = "400ms"
    public static let durReveal = "600ms"
    public static let durCelebrate = "1200ms"
    public static let durLoopPulse = "1600ms"
    public static let stagger = "90ms"
    public static let durPress = "80ms"
    public static let durDragLift = "150ms"
    public static let durDropSettle = "240ms"
    public static let durCollect = "600ms"
    public static let easeStandard = "cubic-bezier(.2,0,0,1)"
    public static let easeEnter = "cubic-bezier(0,0,.2,1)"
    public static let easeExit = "cubic-bezier(.4,0,1,1)"
    public static let easeSpring = "cubic-bezier(.34,1.56,.64,1)"
    public static let easeBounce = "cubic-bezier(.68,-.55,.27,1.55)"
    public static let easeLinear = "linear"
    public static let liftScale = 1.08
    public static let liftTilt = "-4deg"
}

/// OKLCH recipe from tokens.json. SubjectPalette turns a hue into bg, edge, fg, accent, and soft.
public enum TonightRecipe {
    public static let bgLightness = 0.84
    public static let bgChroma = 0.115
    public static let edgeLightness = 0.7
    public static let edgeChroma = 0.12
    public static let fgLightness = 0.33
    public static let fgChroma = 0.12
    public static let accentLightness = 0.68
    public static let accentChroma = 0.17
    public static let softLightness = 0.955
    public static let softChroma = 0.035
}

public struct TonightSubjectName: Hashable, Sendable {
    public var lang: String
    public var text: String

    public init(lang: String, text: String) {
        self.lang = lang
        self.text = text
    }
}

/// One subject from subjects.py, with the hex palette from tokens.json.
public struct TonightSubject: Hashable, Sendable, Identifiable {
    public var id: String
    public var nameEn: String
    public var nameNative: String
    public var lang: String
    public var dir: String
    public var glyphKind: String
    public var glyph: String
    public var hue: Int
    public var group: String
    public var enabledByDefault: Bool
    public var autoMark: Bool
    public var bg: String
    public var edge: String
    public var fg: String
    public var accent: String
    public var soft: String

    public init(
        id: String,
        nameEn: String,
        nameNative: String,
        lang: String,
        dir: String,
        glyphKind: String,
        glyph: String,
        hue: Int,
        group: String,
        enabledByDefault: Bool,
        autoMark: Bool,
        bg: String,
        edge: String,
        fg: String,
        accent: String,
        soft: String
    ) {
        self.id = id
        self.nameEn = nameEn
        self.nameNative = nameNative
        self.lang = lang
        self.dir = dir
        self.glyphKind = glyphKind
        self.glyph = glyph
        self.hue = hue
        self.group = group
        self.enabledByDefault = enabledByDefault
        self.autoMark = autoMark
        self.bg = bg
        self.edge = edge
        self.fg = fg
        self.accent = accent
        self.soft = soft
    }

    /// English name plus the name in the subject's own script.
    public var names: [TonightSubjectName] {
        if lang == "en" {
            return [TonightSubjectName(lang: "en", text: nameNative)]
        }
        return [
            TonightSubjectName(lang: "en", text: nameEn),
            TonightSubjectName(lang: lang, text: nameNative),
        ]
    }
}

public enum TonightSubjects {
    public static let all: [TonightSubject] = [
        TonightSubject(
            id: "maths",
            nameEn: "Maths",
            nameNative: "Maths",
            lang: "en",
            dir: "ltr",
            glyphKind: "icon",
            glyph: "s-maths",
            hue: 262,
            group: "core",
            enabledByDefault: true,
            autoMark: false,
            bg: "#a1cbff",
            edge: "#759ee9",
            fg: "#0f3072",
            accent: "#5c94ff",
            soft: "#e4f1ff"
        ),
        TonightSubject(
            id: "science",
            nameEn: "Science",
            nameNative: "Science",
            lang: "en",
            dir: "ltr",
            glyphKind: "icon",
            glyph: "s-science",
            hue: 195,
            group: "core",
            enabledByDefault: false,
            autoMark: false,
            bg: "#5ee2e2",
            edge: "#00b5b5",
            fg: "#004648",
            accent: "#00b6b9",
            soft: "#d6f8f7"
        ),
        TonightSubject(
            id: "social",
            nameEn: "Social Studies",
            nameNative: "Social Studies",
            lang: "en",
            dir: "ltr",
            glyphKind: "icon",
            glyph: "s-social",
            hue: 60,
            group: "core",
            enabledByDefault: false,
            autoMark: false,
            bg: "#ffb87c",
            edge: "#d58b4b",
            fg: "#5f1e00",
            accent: "#e27900",
            soft: "#ffebd9"
        ),
        TonightSubject(
            id: "evs",
            nameEn: "EVS",
            nameNative: "EVS",
            lang: "en",
            dir: "ltr",
            glyphKind: "icon",
            glyph: "s-evs",
            hue: 142,
            group: "core",
            enabledByDefault: true,
            autoMark: false,
            bg: "#9fde98",
            edge: "#71b16a",
            fg: "#004300",
            accent: "#51b148",
            soft: "#e3f7e1"
        ),
        TonightSubject(
            id: "computers",
            nameEn: "Computers",
            nameNative: "Computers",
            lang: "en",
            dir: "ltr",
            glyphKind: "icon",
            glyph: "s-computers",
            hue: 225,
            group: "core",
            enabledByDefault: false,
            autoMark: false,
            bg: "#6ddaff",
            edge: "#30add6",
            fg: "#003e63",
            accent: "#00abe6",
            soft: "#d8f6ff"
        ),
        TonightSubject(
            id: "gk",
            nameEn: "GK",
            nameNative: "GK",
            lang: "en",
            dir: "ltr",
            glyphKind: "icon",
            glyph: "s-gk",
            hue: 105,
            group: "core",
            enabledByDefault: false,
            autoMark: false,
            bg: "#d5cf73",
            edge: "#aaa23f",
            fg: "#403600",
            accent: "#a99c00",
            soft: "#f3f2d7"
        ),
        TonightSubject(
            id: "art",
            nameEn: "Art",
            nameNative: "Art",
            lang: "en",
            dir: "ltr",
            glyphKind: "icon",
            glyph: "s-art",
            hue: 305,
            group: "core",
            enabledByDefault: false,
            autoMark: false,
            bg: "#dcb7ff",
            edge: "#b08ada",
            fg: "#441f65",
            accent: "#b179eb",
            soft: "#f5ebff"
        ),
        TonightSubject(
            id: "english",
            nameEn: "English",
            nameNative: "English",
            lang: "en",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "Aa",
            hue: 335,
            group: "language",
            enabledByDefault: true,
            autoMark: true,
            bg: "#f9aee8",
            edge: "#cc81bc",
            fg: "#58144d",
            accent: "#d66ac1",
            soft: "#ffe8fa"
        ),
        TonightSubject(
            id: "hindi",
            nameEn: "Hindi",
            nameNative: "हिन्दी",
            lang: "hi",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "अ",
            hue: 30,
            group: "language",
            enabledByDefault: true,
            autoMark: false,
            bg: "#ffae9e",
            edge: "#df8071",
            fg: "#650f08",
            accent: "#ef6856",
            soft: "#ffe8e2"
        ),
        TonightSubject(
            id: "sanskrit",
            nameEn: "Sanskrit",
            nameNative: "संस्कृतम्",
            lang: "sa",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "ॐ",
            hue: 80,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#f2c26f",
            edge: "#c5953b",
            fg: "#542a00",
            accent: "#ce8900",
            soft: "#fdeed6"
        ),
        TonightSubject(
            id: "marathi",
            nameEn: "Marathi",
            nameNative: "मराठी",
            lang: "mr",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "ळ",
            hue: 5,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#ffabc0",
            edge: "#dc7d94",
            fg: "#630c2d",
            accent: "#eb648a",
            soft: "#ffe7ed"
        ),
        TonightSubject(
            id: "punjabi",
            nameEn: "Punjabi",
            nameNative: "ਪੰਜਾਬੀ",
            lang: "pa",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "ੳ",
            hue: 90,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#e8c76e",
            edge: "#bb9b39",
            fg: "#4d2f00",
            accent: "#c19100",
            soft: "#f9f0d6"
        ),
        TonightSubject(
            id: "gujarati",
            nameEn: "Gujarati",
            nameNative: "ગુજરાતી",
            lang: "gu",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "અ",
            hue: 285,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#c2c0ff",
            edge: "#9793e6",
            fg: "#32266f",
            accent: "#9085fb",
            soft: "#ededff"
        ),
        TonightSubject(
            id: "bengali",
            nameEn: "Bengali",
            nameNative: "বাংলা",
            lang: "bn",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "অ",
            hue: 165,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#7be2b8",
            edge: "#46b68c",
            fg: "#004725",
            accent: "#00b87d",
            soft: "#dcf8ea"
        ),
        TonightSubject(
            id: "odia",
            nameEn: "Odia",
            nameNative: "ଓଡ଼ିଆ",
            lang: "or",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "ଅ",
            hue: 245,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#88d2ff",
            edge: "#58a5e4",
            fg: "#00376e",
            accent: "#069ff9",
            soft: "#ddf3ff"
        ),
        TonightSubject(
            id: "telugu",
            nameEn: "Telugu",
            nameNative: "తెలుగు",
            lang: "te",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "అ",
            hue: 15,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#ffabb2",
            edge: "#df7e86",
            fg: "#650c21",
            accent: "#ee6476",
            soft: "#ffe7e9"
        ),
        TonightSubject(
            id: "tamil",
            nameEn: "Tamil",
            nameNative: "தமிழ்",
            lang: "ta",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "அ",
            hue: 350,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#ffabd5",
            edge: "#d67ea9",
            fg: "#5e0f3e",
            accent: "#e266a7",
            soft: "#ffe7f3"
        ),
        TonightSubject(
            id: "kannada",
            nameEn: "Kannada",
            nameNative: "ಕನ್ನಡ",
            lang: "kn",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "ಅ",
            hue: 120,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#c1d67e",
            edge: "#95a94e",
            fg: "#2f3c00",
            accent: "#8ca600",
            soft: "#edf4da"
        ),
        TonightSubject(
            id: "malayalam",
            nameEn: "Malayalam",
            nameNative: "മലയാളം",
            lang: "ml",
            dir: "ltr",
            glyphKind: "glyph",
            glyph: "അ",
            hue: 180,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#68e3cd",
            edge: "#24b6a1",
            fg: "#004738",
            accent: "#00b89c",
            soft: "#d8f8f1"
        ),
        TonightSubject(
            id: "urdu",
            nameEn: "Urdu",
            nameNative: "اردو",
            lang: "ur",
            dir: "rtl",
            glyphKind: "glyph",
            glyph: "ب",
            hue: 155,
            group: "language",
            enabledByDefault: false,
            autoMark: false,
            bg: "#8ae1aa",
            edge: "#59b47d",
            fg: "#004616",
            accent: "#00b667",
            soft: "#dff8e6"
        )
    ]

    public static let classDefaults: [Int: [String]] = [
        1: ["english", "hindi", "maths", "evs"],
        2: ["english", "hindi", "maths", "evs"],
        3: ["english", "hindi", "maths", "evs"]
    ]

    public static let autoMark: Set<String> = ["english"]

    public static let scriptFonts: [String: String] = [
        "hi": "Noto Sans Devanagari",
        "sa": "Noto Sans Devanagari",
        "mr": "Noto Sans Devanagari",
        "pa": "Noto Sans Gurmukhi",
        "gu": "Noto Sans Gujarati",
        "bn": "Noto Sans Bengali",
        "or": "Noto Sans Oriya",
        "te": "Noto Sans Telugu",
        "ta": "Noto Sans Tamil",
        "kn": "Noto Sans Kannada",
        "ml": "Noto Sans Malayalam",
        "ur": "Noto Nastaliq Urdu"
    ]

    public static func record(_ id: String) -> TonightSubject? {
        all.first { $0.id == id }
    }
}
