#!/usr/bin/env python3
"""Generate DesignSystem Swift from tokens.json and subjects.py.

Sources live next to this script (design v3):
  tokens.json — colour hex, type, space, and subject palettes
  subjects.py — subject rows, class defaults, and the auto-mark set

Regenerate from this directory:
  python3 generate_design_system.py
"""

import importlib.util
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "Sources" / "DesignSystem" / "GeneratedTokens.swift"


def camel(name: str) -> str:
    parts = name.split("-")
    ident = parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])
    if ident[:1].isdigit():
        ident = "n" + ident
    return ident


def swift_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_subjects():
    spec = importlib.util.spec_from_file_location("tonight_subjects", HERE / "subjects.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def static_lets(mapping, indent="    "):
    lines = []
    for key, value in mapping.items():
        name = camel(key)
        if isinstance(value, str):
            rendered = swift_string(value)
        elif isinstance(value, bool):
            rendered = "true" if value else "false"
        elif isinstance(value, int) and not isinstance(value, bool):
            rendered = str(value)
        elif isinstance(value, float):
            rendered = format(value, "g")
        else:
            raise SystemExit(f"unsupported token {key}: {value!r}")
        lines.append(f"{indent}public static let {name} = {rendered}")
    return "\n".join(lines)


def subject_swift(row, colors, defaults, auto_mark):
    sid, name_en, name_native, lang, direction, glyph_kind, glyph, hue, group = row
    palette = colors[sid]
    enabled = "true" if sid in defaults else "false"
    auto = "true" if sid in auto_mark else "false"
    return "\n".join([
        "        TonightSubject(",
        f"            id: {swift_string(sid)},",
        f"            nameEn: {swift_string(name_en)},",
        f"            nameNative: {swift_string(name_native)},",
        f"            lang: {swift_string(lang)},",
        f"            dir: {swift_string(direction)},",
        f"            glyphKind: {swift_string(glyph_kind)},",
        f"            glyph: {swift_string(glyph)},",
        f"            hue: {int(hue)},",
        f"            group: {swift_string(group)},",
        f"            enabledByDefault: {enabled},",
        f"            autoMark: {auto},",
        f"            bg: {swift_string(palette['bg'])},",
        f"            edge: {swift_string(palette['edge'])},",
        f"            fg: {swift_string(palette['fg'])},",
        f"            accent: {swift_string(palette['accent'])},",
        f"            soft: {swift_string(palette['soft'])}",
        "        )",
    ])


def main():
    tokens = json.loads((HERE / "tokens.json").read_text(encoding="utf-8"))
    subjects = load_subjects()
    defaults = {sid for ids in subjects.CLASS_DEFAULTS.values() for sid in ids}
    missing = [row[0] for row in subjects.SUBJECTS if row[0] not in tokens["subjects"]]
    if missing:
        raise SystemExit(f"tokens.json is missing subjects: {missing}")

    recipe = tokens["recipe"]
    subject_rows = ",\n".join(
        subject_swift(row, tokens["subjects"], defaults, subjects.AUTO_MARK)
        for row in subjects.SUBJECTS
    )
    class_lines = []
    for school_class, ids in subjects.CLASS_DEFAULTS.items():
        rendered = ", ".join(swift_string(sid) for sid in ids)
        class_lines.append(f"        {school_class}: [{rendered}]")
    font_lines = []
    for lang, font in subjects.SCRIPT_FONTS.items():
        font_lines.append(f"        {swift_string(lang)}: {swift_string(font)}")
    auto = ", ".join(swift_string(sid) for sid in sorted(subjects.AUTO_MARK))
    class_block = ",\n".join(class_lines)
    font_block = ",\n".join(font_lines)

    swift = f"""// Generated by generate_design_system.py from tokens.json and subjects.py.
// Do not edit by hand.
// Regenerate from ios/Packages/Tonight/codegen/design:
//   python3 generate_design_system.py

import Foundation

public enum TonightPalette {{
{static_lets(tokens["color"])}
}}

public enum TonightType {{
    public enum Font {{
{static_lets(tokens["font"], indent="        ")}
    }}

    public enum Text {{
{static_lets(tokens["text"], indent="        ")}
    }}

    public enum Weight {{
{static_lets(tokens["weight"], indent="        ")}
    }}

    public enum Leading {{
{static_lets(tokens["leading"], indent="        ")}
    }}
}}

public enum TonightSpace {{
{static_lets(tokens["space"])}
}}

public enum TonightRadius {{
{static_lets(tokens["radius"])}
}}

public enum TonightSize {{
{static_lets(tokens["size"])}
}}

public enum TonightEdge {{
{static_lets(tokens["edge"])}
}}

/// Reserved durations and easings. v1 screens stay still (TonightMotion.animationsInV1 is false).
public enum TonightMotionToken {{
{static_lets(tokens["motion"])}
}}

/// OKLCH recipe from tokens.json. SubjectPalette turns a hue into bg, edge, fg, accent, and soft.
public enum TonightRecipe {{
    public static let bgLightness = {recipe["bg"]["l"]}
    public static let bgChroma = {recipe["bg"]["c"]}
    public static let edgeLightness = {recipe["edge"]["l"]}
    public static let edgeChroma = {recipe["edge"]["c"]}
    public static let fgLightness = {recipe["fg"]["l"]}
    public static let fgChroma = {recipe["fg"]["c"]}
    public static let accentLightness = {recipe["accent"]["l"]}
    public static let accentChroma = {recipe["accent"]["c"]}
    public static let softLightness = {recipe["soft"]["l"]}
    public static let softChroma = {recipe["soft"]["c"]}
}}

public struct TonightSubjectName: Hashable, Sendable {{
    public var lang: String
    public var text: String

    public init(lang: String, text: String) {{
        self.lang = lang
        self.text = text
    }}
}}

/// One subject from subjects.py, with the hex palette from tokens.json.
public struct TonightSubject: Hashable, Sendable, Identifiable {{
    public var id: String
    public var nameEn: String
    public var nameNative: String
    public var lang: String
    public var dir: String
    public var glyphKind: String
    public var glyph: String
    public var hue: Int
    public var group: String
    public var enabledByDefault: Bool
    public var autoMark: Bool
    public var bg: String
    public var edge: String
    public var fg: String
    public var accent: String
    public var soft: String

    public init(
        id: String,
        nameEn: String,
        nameNative: String,
        lang: String,
        dir: String,
        glyphKind: String,
        glyph: String,
        hue: Int,
        group: String,
        enabledByDefault: Bool,
        autoMark: Bool,
        bg: String,
        edge: String,
        fg: String,
        accent: String,
        soft: String
    ) {{
        self.id = id
        self.nameEn = nameEn
        self.nameNative = nameNative
        self.lang = lang
        self.dir = dir
        self.glyphKind = glyphKind
        self.glyph = glyph
        self.hue = hue
        self.group = group
        self.enabledByDefault = enabledByDefault
        self.autoMark = autoMark
        self.bg = bg
        self.edge = edge
        self.fg = fg
        self.accent = accent
        self.soft = soft
    }}

    /// English name plus the name in the subject's own script.
    public var names: [TonightSubjectName] {{
        if lang == "en" {{
            return [TonightSubjectName(lang: "en", text: nameNative)]
        }}
        return [
            TonightSubjectName(lang: "en", text: nameEn),
            TonightSubjectName(lang: lang, text: nameNative),
        ]
    }}
}}

public enum TonightSubjects {{
    public static let all: [TonightSubject] = [
{subject_rows}
    ]

    public static let classDefaults: [Int: [String]] = [
{class_block}
    ]

    public static let autoMark: Set<String> = [{auto}]

    public static let scriptFonts: [String: String] = [
{font_block}
    ]

    public static func record(_ id: String) -> TonightSubject? {{
        all.first {{ $0.id == id }}
    }}
}}
"""
    OUT.write_text(swift, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
