"""Single source of truth for the subject system. build.py turns this into shared/subjects.css
and the {{badge}} / {{sname}} template tags. Add a subject = add one row here."""
# id, english name, native name (own script), lang tag, dir, glyph kind ("icon" = line icon symbol, else script glyph text), glyph, hue (oklch), group
SUBJECTS = [
  ("maths",     "Maths",           "Maths",      "en", "ltr", "icon", "s-maths", 262, "core"),
  ("science",   "Science",         "Science",    "en", "ltr", "icon", "s-science", 195, "core"),
  ("social",    "Social Studies",  "Social Studies","en","ltr","icon", "s-social", 60, "core"),
  ("evs",       "EVS",             "EVS",        "en", "ltr", "icon", "s-evs", 142, "core"),
  ("computers", "Computers",       "Computers",  "en", "ltr", "icon", "s-computers", 225, "core"),
  ("gk",        "GK",              "GK",         "en", "ltr", "icon", "s-gk", 105, "core"),
  ("art",       "Art",             "Art",        "en", "ltr", "icon", "s-art", 305, "core"),
  ("english",   "English",         "English",    "en", "ltr", "glyph","Aa", 335, "language"),
  ("hindi",     "Hindi",           "हिन्दी",      "hi", "ltr", "glyph","अ", 30, "language"),
  ("sanskrit",  "Sanskrit",        "संस्कृतम्",    "sa", "ltr", "glyph","ॐ", 80, "language"),
  ("marathi",   "Marathi",         "मराठी",       "mr", "ltr", "glyph","ळ", 5, "language"),
  ("punjabi",   "Punjabi",         "ਪੰਜਾਬੀ",      "pa", "ltr", "glyph","ੳ", 90, "language"),
  ("gujarati",  "Gujarati",        "ગુજરાતી",     "gu", "ltr", "glyph","અ", 285, "language"),
  ("bengali",   "Bengali",         "বাংলা",       "bn", "ltr", "glyph","অ", 165, "language"),
  ("odia",      "Odia",            "ଓଡ଼ିଆ",       "or", "ltr", "glyph","ଅ", 245, "language"),
  ("telugu",    "Telugu",          "తెలుగు",      "te", "ltr", "glyph","అ", 15, "language"),
  ("tamil",     "Tamil",           "தமிழ்",       "ta", "ltr", "glyph","அ", 350, "language"),
  ("kannada",   "Kannada",         "ಕನ್ನಡ",       "kn", "ltr", "glyph","ಅ", 120, "language"),
  ("malayalam", "Malayalam",       "മലയാളം",     "ml", "ltr", "glyph","അ", 180, "language"),
  ("urdu",      "Urdu",            "اردو",        "ur", "rtl", "glyph","ب", 155, "language"),
]
BY_ID = {s[0]: s for s in SUBJECTS}

SCRIPT_FONTS = {
  "hi": "Noto Sans Devanagari", "sa": "Noto Sans Devanagari", "mr": "Noto Sans Devanagari",
  "pa": "Noto Sans Gurmukhi", "gu": "Noto Sans Gujarati", "bn": "Noto Sans Bengali", "or": "Noto Sans Oriya",
  "te": "Noto Sans Telugu", "ta": "Noto Sans Tamil", "kn": "Noto Sans Kannada", "ml": "Noto Sans Malayalam",
  "ur": "Noto Nastaliq Urdu",
}

ROLES = ["bg", "fg", "accent", "soft"]

def css():
    out = ["/* GENERATED by build.py from subjects.py — do not edit by hand. */",
           "/* Each concept sets the 8 recipe knobs (--recipe-<role>-l / -c) on [data-concept];",
           "   every subject then gets --subj-<id>-bg / -fg / -accent / -soft from its hue.",
           "   Per-subject hand overrides go in the concept file after this one. */",
           "[data-concept] {"]
    for sid, *_r in SUBJECTS:
        h = BY_ID[sid][7]
        out.append(f"  --subj-{sid}-h: {h};")
    for sid, *_r in SUBJECTS:
        for role in ROLES:
            out.append(f"  --subj-{sid}-{role}: oklch(var(--recipe-{role}-l) var(--recipe-{role}-c) var(--subj-{sid}-h));")
    out.append("}")
    out.append("/* Scope: anything inside data-subject=\"x\" can just use --s-bg / --s-fg / --s-accent / --s-soft. */")
    for sid, *_r in SUBJECTS:
        out.append(f'[data-subject="{sid}"] {{ --s-bg: var(--subj-{sid}-bg); --s-fg: var(--subj-{sid}-fg); --s-accent: var(--subj-{sid}-accent); --s-soft: var(--subj-{sid}-soft); }}')
    out.append("/* Script fonts: every native name/glyph carries lang=…; Urdu also carries dir=rtl. */")
    groups = {}
    for lang, font in SCRIPT_FONTS.items():
        groups.setdefault(font, []).append(lang)
    for font, langs in groups.items():
        sel = ", ".join(f":lang({l})" for l in langs)
        out.append(f'{sel} {{ font-family: "{font}", var(--font-child, sans-serif); }}')
    out.append(':lang(ur) { line-height: 1.9; }')
    return "\n".join(out) + "\n"

# ---- Scope (PM, Oct 2026): classes 1-3 only, ages 6-8 ----
CLASSES = [1, 2, 3]
# Default subjects per class. Everything else in SUBJECTS is optional and is
# added by the parent in the subject picker.
CLASS_DEFAULTS = {1: ["english", "hindi", "maths", "evs"],
                  2: ["english", "hindi", "maths", "evs"],
                  3: ["english", "hindi", "maths", "evs"]}
# Read-aloud auto-marking is available for these subjects only; all others
# end in the "awaiting-check" (Parent checks) state.
AUTO_MARK = {"english"}

def optional_for(cls):
    return [s[0] for s in SUBJECTS if s[0] not in CLASS_DEFAULTS[cls]]
